### ISSUE TITLE
[question] - 앱 테마 색상이 변경된 것에 관해

### ISSUE THREAD

**Issue by gksgpd97** [ReadyItGo-A-level/Frontend#20]
## 관련 이미지
<div style="display:inline-block">
<img src="https://user-images.githubusercontent.com/35549958/179402210-f28f82a5-1383-4fd5-a762-574303adbbdf.png" width="40%"/>
<img src="https://user-images.githubusercontent.com/35549958/179402223-de89a188-8e68-44c1-8812-b7757c7c3880.png" width="40%"/>
</div>

## 질문 내용
- 원래 앱 기본 백그라운드 색상이 흰색이었는데 회색이 되어 버렸습니다
- 원래 앱 바텀 네비게이션 뷰 색상도 검정으로 변경되었습니다.
- 앱 테마 색상 관련된 themes 패키지 내용을 수정하신 분 계실까요?

**Comment by songfox00** [comment]
AndroidManifest.xml에 theme을 @style/Theme.AppCompat.Light.NoActionBar
이걸로 변경하고 
res/values/heme.xml에서 <style name="Theme.Alevel" parent="Theme.MaterialComponents.DayNight.NoActionBar"> 을 <style name="Theme.Alevel" parent="Theme.MaterialComponents.Light.NoActionBar"> 이걸로 바꿔보시겠어요?

**Comment by songfox00** [comment]
이거 저때문일 수도...?ㅎ
