### ISSUE TITLE
[feat] - 마이페이지

### ISSUE THREAD

**Issue by JI00000** [ReadyItGo-A-level/Frontend#4]
마이 페이지 기능 구현 중입니다.

마이페이지 
- 마이패이지 메인 ✅️
- 계정 상세보기 ✅️
- 스크랩 (게시글 / 술)
- 작성 목록 (게시글 / 댓글)
- 술 제보 
- 비밀번호 변경
- 설정

✨️ 술 제보, 비밀번호 변경, 설정은 액티비티로 나머지 화면은 프래그먼트로 구성됩니다.

**Comment by gksgpd97** [comment]
description 적어주세요!!

**Comment by JI00000** [comment]
> description 적어주세요!!

작성했습니다!! 말씀 감사합니다~

**Comment by gksgpd97** [comment]
전체 피드보기 하시는 건 아니지만 까먹을까봐 미리 댓글 달아 놓습니다. 리싸이클러뷰 구현하다가 아이템 크기가 일정하지 않을 때 쓰는 레이아웃매니저 (StaggeredGridLayoutManager)가 있는 것 같아서 링크 공유합니다.
https://velog.io/@5y145/RecyclerView
